name: Krypto Alarm Cronjob

on:
  schedule:
    # Läuft alle 15 Minuten rund um die Uhr
    - cron: '*/5 * * * *'
  workflow_dispatch: # Ermöglicht es dir, das Skript jederzeit manuell per Klick zu testen

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Python einrichten
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Abhaengigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Skript ausfuehren
        env:
          # Diese Namen müssen exakt mit os.environ.get() im Python-Code übereinstimmen
          BLOCKFROST_PROJECT_ID: ${{ secrets.BLOCKFROST_PROJECT_ID }}
          PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
          PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}
        # Das "-u" sorgt dafür, dass die Textausgabe sofort im Live-Log erscheint
        run: python -u preisalarm.py
